apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-toleration-webhook
  labels:
    app: pod-toleration-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-toleration-webhook
  template:
    metadata:
      labels:
        app: pod-toleration-webhook
    spec:
      containers:
        - name: server
          image: jayprim/pod-toleration-webhook:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8443
              name: webhook-api
          volumeMounts:
            - name: pod-toleration-webhook
              mountPath: /run/secrets/tls
              readOnly: true
      volumes:
        - name: pod-toleration-webhook
          secret:
            secretName: pod-toleration-webhook-tls