apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- webhook-configuration.yaml
- deployment.yaml
- service.yaml
namespace: kubeflow
secretGenerator:
- name: pod-toleration-webhook-tls
  files:
    - secret/webhook-server-tls.crt
    - secret/webhook-server-tls.key
  type: "kubernetes.io/tls"